services:
  postgres:
    container_name: labs-fav-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: labs-fav
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  redis:
    container_name: labs-fav-redis
    image: redis:7-alpine
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
